product: tbronson-pentest
team_name: offsec
general:
  notifications:
    slack_channels:
      - "offsec-deployments"
  team_jenkins: csecbuilds
  dry_run: false
  allow_parallel_deployments: true
  start_environment_automatically: true
  split_terraform_phases: true
  environments_order:
    sequential:
      - concurrent:
        - dev
      - concurrent:
        - dep
phases:
  terraform:
    source: terraform
    terragrunt_path: ""
observatory:
  no_endpoint: true

package_rollout:
  only_consider_changes_in_directories:
    - src/

